resources:
- manager.yaml
- credentials.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: example.com/cluster-api-provider-huawei
  newTag: v0.0.1
