name: Releases
on:
  push:
    branches:
      - master-dev

env:
  PUSH: 'true'
  PRE_RELEASE: GA
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO_VERSION: "1.22.0"

permissions:
  contents: write
  packages: write

jobs:
  releases:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ghcr.io
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          make docker-buildx
